var data_config = {
    tag: "visualization",
    mode: "gsheets",
    service_name: "Google Sheets",
    
    bubble_min_scale: 1.1,
    bubble_max_scale: 1.1,
    
    paper_min_scale: 1,

    title: "Knowledge Map of <b>Covid-19 research</b>",
    input_format: "json",
    base_unit: "questions",
    use_area_uri: true,
    preview_type: "pdf",
    
    show_multiples: false,
    show_dropdown: false,
    show_intro: false,
    show_list:true,
    is_force_papers: true,
    is_title_clickable: false,
    show_infolink: true,
    show_infolink_areas: false,
	
    show_context: true,
    create_title_from_context: false,
    show_context_timestamp: true,
    show_loading_screen: true,
    
    scale_toolbar: false,
    
    content_based: true,
    
    is_force_areas: true,
    area_force_alpha: 0.03,
    papers_force_alpha: 0.2,
    
    language: "eng_covis",
    
    sort_options: ["year", "title", "area"],
    filter_options: ["all", "Journal Article", "Preprint", "ReFigure", "Review"],
    filter_field: "resulttype",
    
    show_keywords: true,
    hide_keywords_overview: false,
    show_tags: true,
    show_comments: true,
    show_resulttype: true,
    
    sort_menu_dropdown: true,
    filter_menu_dropdown: true,
    
    share_modal: true,
    hashtags_twitter_card: "COVID19,openscience,discovery",
    
    intro: {
      title:"Knowledge Map of Covid-19 research curated by subject matter experts"
      , body: "<h3>About Covis</h3><p>In the current pandemic, many researchers seek valid scientific data and findings on Covid-19. To support them, Open Knowledge Maps and ReFigure have launched CoVis. CoVis provides a curated knowledge map of seminal works on Covid-19 research. The knowledge map is constantly evolving thanks to the collective editing of subject-matter experts.</p><p><a class='link-popup' href='faqs'>Read our FAQs to find out more</a>.</p><h3>Data Source curated by ReFigure</h3><p>Given the fast pace of research and the limited historical data on Covid-19, many findings are under debate and only understandable after reading several reports from different sources.</p><p>Team <a target='_blank' class='link-popup' href='https://refigure.org/'>ReFigure</a> creates visual, easy to understand, annotated, figure collections which provide analyses and consensus on key issues. Boston based scientists and ReFigure founders Drs. Goyal and Akin are immunology experts and also form our starting database curation team.</p><p>They are also looking for subject-matter experts to help them in their efforts.</p><p><a class='link-popup' target='_blank' href='contact-us'>Please get in touch</a>, if you'd like to add research to the data source.</p><h3>Software created by Open Knowledge Maps</h3><p>CoVis visualization is achieved using award-winning software <a target='_blank' class='link-popup' href='https://openknowledgemaps.org/'>developed by Open Knowledge Maps</a>. The software creates visual overviews of research fields, alongside relevant resources, annotated with keywords, comments and tags. The visual interface allows the user to explore a large amount of resources with ease on a single page and all the publications are linked; those that are open access can be downloaded directly from the interface.</p>"
    },
    
    localization: {
        eng_covis: {
            loading: "Updating and retrieving map. This may take a few seconds, please hold on.",
            search_placeholder: "Search within map...",
            show_list: "Show list",
            hide_list: "Hide list",
            intro_label: "curated by subject matter experts",
            intro_icon: "",
            relevance: "relevance",
            readers: "citations",
            year: "date",
            authors: "authors",
            title: "title",
            area: "Area",
            backlink: "← Back to overview",
            backlink_list: "← Show all documents in area",
            backlink_list_streamgraph: "← Show all documents",
            backlink_list_streamgraph_stream_selected: "← Show all documents in stream",
            keywords: "Keywords",
            no_keywords: "n/a",
            no_title: "No title",
            overview_label: 'Overview of',
            streamgraph_label: 'Streamgraph for',
            overview_authors_label: 'Overview of the works of',
            streamgraph_authors_label: 'Streamgraph for the works of',
            articles_label: 'documents',
            most_recent_label: 'most recent',
            most_relevant_label: 'most relevant',
            most_relevant_tooltip: 'To determine the most relevant documents, we use the relevance ranking provided by the source - either BASE or PubMed. Both sources compute the text similarity between your query and the article metadata to establish the relevance ranking. Please consult the FAQ for more information.',
            source_label: 'Source',
            resulttype_label: 'Document type',
            documenttypes_label: 'Document types',
            timestamp_label: 'Last updated',
            documenttypes_tooltip: 'The following document types were taken into consideration in the creation of this map (not all of them may appear in the map):',
            default_area: "No area",
            default_author: "",
            default_id: "defaultid",
            default_hash: "hashHash",
            default_abstract: "No Abstract",
            default_published_in: "",
            default_readers: 0,
            default_url: "",
            default_x: 1.,
            default_y: 1.,
            default_year: "",
            sort_by_label: 'sort by:',
            filter_by_label: 'show: ',
            all: "any",
            open_access: "Open Access",
            "Journal Article": "Journal article",
            Preprint: "Preprint",
            ReFigure: "ReFigure",
            Review: "Review",
            link: 'link',
            items: "items",
            pdf_not_loaded: "Sorry, we were not able to retrieve the PDF for this publication. You can get it directly from",
            pdf_not_loaded_linktext: "this website",
            share_button_title: "share this map",
            embed_button_title: "Embed this knowledge map on other websites",
            embed_button_text: 'Copy',
            embed_title: 'embed map',
            embed_body_text: 'You can use this code to embed the visualization on your own website or in a dashboard.',
        },
    }
};
