var data_config = {
    tag: "visualization",
    mode: "local_files",
    service_name: "CoVis",
    
    bubble_min_scale: 1.2,
    bubble_max_scale: 1.1,
    
    paper_min_scale: 0.8,

    title: "Knowledge Map of <b>Covid-19 research</b>",
    input_format: "json",
    base_unit: "questions",
    use_area_uri: true,
    preview_type: "pdf",
    
    show_multiples: false,
    show_dropdown: false,
    show_intro: false,
    show_list:true,
    is_force_papers: true,
    is_title_clickable: false,
    show_infolink: false,
    show_infolink_areas: false,
	
    show_context: true,
    create_title_from_context: false,
    show_context_timestamp: true,
    
    scale_toolbar: false,
    
    content_based: true,
    
    is_force_areas: true,
    area_force_alpha: 0.03,
    papers_force_alpha: 0.2,
    
    language: "eng_covis",
    
    sort_options: ["year", "title", "area"],
    filter_options: ["all", "Journal Article", "Preprint", "ReFigure", "Review"],
    filter_field: "resulttype",
    
    show_keywords: true,
    hide_keywords_overview: false,
    show_tags: true,
    show_comments: true,
    show_resulttype: true,
    
    sort_menu_dropdown: true,
    filter_menu_dropdown: true,
    
    localization: {
        eng_covis: {
            loading: "Loading...",
            search_placeholder: "Search within map...",
            show_list: "Show list",
            hide_list: "Hide list",
            intro_label: "",
            intro_icon: "&#xf05a;",
            relevance: "relevance",
            readers: "citations",
            year: "year",
            authors: "authors",
            title: "title",
            area: "Area",
            backlink: "← Back to overview",
            backlink_list: "← Show all documents in area",
            backlink_list_streamgraph: "← Show all documents",
            backlink_list_streamgraph_stream_selected: "← Show all documents in stream",
            keywords: "Keywords",
            no_title: "No title",
            overview_label: 'Overview of',
            streamgraph_label: 'Streamgraph for',
            overview_authors_label: 'Overview of the works of',
            streamgraph_authors_label: 'Streamgraph for the works of',
            articles_label: 'documents',
            most_recent_label: 'most recent',
            most_relevant_label: 'most relevant',
            most_relevant_tooltip: 'To determine the most relevant documents, we use the relevance ranking provided by the source - either BASE or PubMed. Both sources compute the text similarity between your query and the article metadata to establish the relevance ranking. Please consult the FAQ for more information.',
            source_label: 'Source',
            resulttype_label: 'Document type',
            documenttypes_label: 'Document types',
            timestamp_label: 'Last updated',
            documenttypes_tooltip: 'The following document types were taken into consideration in the creation of this map (not all of them may appear in the map):',
            default_area: "No area",
            default_author: "",
            default_id: "defaultid",
            default_hash: "hashHash",
            default_abstract: "No Abstract",
            default_published_in: "",
            default_readers: 0,
            default_url: "",
            default_x: 1.,
            default_y: 1.,
            default_year: "",
            sort_by_label: 'sort by:',
            filter_by_label: 'show: ',
            all: "any",
            open_access: "Open Access",
            "Journal Article": "Journal article",
            Preprint: "Preprint",
            ReFigure: "ReFigure",
            Review: "Review",
            link: 'link',
            items: "items",
            pdf_not_loaded: "Sorry, we were not able to retrieve the PDF for this publication. You can get it directly from",
            pdf_not_loaded_linktext: "this website",
            share_button_title: "share this map",
            embed_button_title: "Embed this knowledge map on other websites",
            embed_button_text: 'Copy',
            embed_title: 'embed map',
            embed_body_text: 'You can use this code to embed the visualization on your own website or in a dashboard.',
        },
    }
};
